# Dependencies
markdown:         kramdown
redcarpet:
  extensions: [tables, with_toc_data]
highlighter:      rouge

# Permalinks
permalink:        pretty

excerpt_separator: <!--more-->

# Setup
title:            HookRace Blog
tagline:          Just a blog for now
url:              https://hookrace.net
baseurl:          /
author:
  name:           Dennis Felsing
  url:            http://felsin9.de/nnis
  email:          dennis@felsin9.de

pages_list:
  Posts: '/blog/'
  Feed: '/blog/feed/'
  DDNet: 'https://ddnet.org/'
  Me: 'http://felsin9.de/nnis/'
  Switch Theme: '/switch-theme/'

#gems: [jekyll-tagging]

tag_page_layout:  tag_page
tag_page_dir:     blog

tag_feed_layout:  tag_feed
tag_feed_dir:     blog/feed

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/HookRace/hookrace-web
