# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [tables, with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        pretty

excerpt_separator: <!--more-->

# Setup
title:            HookRace - a Nim blog for now
tagline:          The successor of DDraceNetwork
url:              https://hookrace.net
baseurl:          /
author:
  name:           Dennis Felsing
  url:            http://felsin9.de/nnis
  email:          dennis@felsin9.de

pages_list:
  Posts: '/blog/'
  Feed: '/blog/feed/'
  DDNet: 'https://ddnet.tw/'
  Me: 'http://felsin9.de/nnis/'

#gems: [jekyll-tagging]

tag_page_layout:  tag_page
tag_page_dir:     blog

tag_feed_layout:  tag_feed
tag_feed_dir:     blog/feed

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
